services:
  health-db:
    image: postgres:latest
    networks:
      - health_be
    restart: on-failure
    ports:
      - "9084:5432"
    env_file:
      - ./.env
    volumes:
      - "./health-db/pg_data:/var/lib/postgresql/data"
      # - "./health-db/01-createdb.sql:/docker-entrypoint-initdb.d/01-createdb.sql"
      - "./health-db/02-createtables.sql:/docker-entrypoint-initdb.d/02-createtables.sql"
      - "./health-db/04-add-tandem-insulin-tables.sql:/docker-entrypoint-initdb.d/04-add-tandem-insulin-tables.sql"
      - "./health-db/05-add-tandem-cgm-table.sql:/docker-entrypoint-initdb.d/05-add-tandem-cgm-table.sql"
  health-sync:
    networks:
      - health_be
    build: ./health-sync
    restart: always
    env_file:
      - ./.env
      - ./health-sync/.env
    environment:
      - DB_SSL_MODE=disable
    depends_on:
      - health-db
  health-mongo-sync:
    networks:
      - health_be
    build: ./health-mongo-sync
    restart: "no"           # run once; use a one-shot restart policy
    env_file:
      - ./.env
      - ./health-mongo-sync/.env
    environment:
      - DB_SSL_MODE=disable
    depends_on:
      - health-db
  tandemsync:
    networks:
      - health_be
    build:
      context: ./health-tandem-sync
      dockerfile: Dockerfile.tandemsync
    restart: always
    env_file:
      - ./.env
      - ./health-tandem-sync/.env
    environment:
      - DB_SSL_MODE=disable
      - SYNC_INTERVAL_SECONDS=3600
    depends_on:
      - health-db
  health-api:
    networks:
      - health_fe
      - health_be
    build: ./health-api
    ports:
      - "9082:8080"
    restart: on-failure
    env_file:
      - ./.env
      - ./health-api/.env
    depends_on:
      - health-db
  health-fe:
    networks:
      - health_fe
    build:
      context: ./health-fe
      args:
        VITE_API_URL: http://localhost:9082
    ports:
      - "9083:80"
    restart: on-failure
    depends_on:
      - health-api
  pgadmin:
    image: dpage/pgadmin4:9.12
    networks:
      - health_be
    ports:
      - 9085:80
    env_file:
      - ./pgadmin/.env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
networks:
  health_fe:
    driver: bridge
  health_be:
    driver: bridge
